name: Linter
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Linter:
    runs-on: ubuntu-latest
    steps:
      - run: echo " The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo " This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo " branch=${{ github.ref }}, commit_hash=${{ github.sha }}."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Updated files
        run: git diff-tree --no-commit-id --name-only ${{ github.sha }} -r